config/routes.rb
Rails.application.routes.draw do
  get 'chatroom/room'
  resources :chat_messages, only: :create

  get 'sessions/create'

  get 'sessions/destroy'

  get 'sessions/auth_fail'

get   '/login', :to => 'sessions#new', :as => :login
get '/auth/:provider/callback', to: 'sessions#create'
get '/auth/failure', to: 'sessions#auth_fail'
get '/sign_out', to: 'sessions#destroy', as: :sign_out

get  '/chatroom' => 'chatroom#room', :as => :chat

   root 'chatroom#front'

end

app/models/chatroom.rb
class Chatroom < ActiveRecord::Base
belongs_to :quiz
end

app/models/quiz.rb
class Quiz < ActiveRecord::Base
 has_many :chatrooms
end

app/models/user.rb
class User < ActiveRecord::Base
  class << self
    def from_omniauth(auth)
      provider = auth.provider
      uid = auth.uid
      info = auth.info.symbolize_keys!
      user = User.find_or_initialize_by(uid: uid, provider: provider)
      user.name = info.name
      user.avatar_url = info.image
      user.profile_url = info.urls.send(provider.capitalize.to_sym)
      user.save!
      user
# need to add score somehow...
    end
  end
 end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user
  attr_accessor :current_user, :quiz

  protected

  def authenticate_user
    if cookies[:user_id]
      self.current_user = User.find(cookies[:user_id])
    end

    # TODO: Move to someting like
    # app_requires_auth = Rails.config.requires_authentication
    app_requires_auth = !Rails.env.development?

    unless app_requires_auth
      # use anonymous user to support current_user interface when not logged in.
      anonymous_user = AnonymousUser.new(name: 'Anonymous')
      self.current_user ||= anonymous_user
    end

    redirect_to login_url, notice: "You must be logged in to access." unless current_user
  end

  # this makes it available to all of our controllers since everything inherits from Application Controller
  # def current_user
  #   @current_user
  # end

  # def current_user=(value)
  #   @current_user = value
  # end

  def user
    @user
  end

  def user=(value)
    @user = value
  end

  # this makes it available to our views.
  helper_method :current_user, :user
end

# created to update score and user for anonymous
class AnonymousUser
  attr_accessor :name, :score
  def initialize(params = {})
    update(params)
  end

  def update(params)
    params.each do |key, value|
      self.send("#{key}=", value)
    end
  end
end

app/controllers/chat_messages_controller.rb
class ChatMessagesController < ApplicationController
  # all publishing events are being handled by this controller function. We are listening for the :message params.
  def create
    message_user = current_user.name
    message = params[:message]
    # we are  passing in the chatroom id currently to just a chatroom of 1
    chatroom = Chatroom.find(params[:chatroom_id])
    user_scores= false
    case message
    when /@ROBOT/i
      message_user = 'ROBOT'
      message = "I haz ALL the javascripts!  Want some?"
    when /@QUIZ/i
      if !chatroom.game_mode #we want game mode default to false
        random_quiz = Quiz.all.sample
        random_id= random_quiz.id  #dont need this maybe up for deletion.
        random_question= random_quiz.question

        message_user = 'ROBOT_QUIZ'
        message = random_question

        chatroom.quiz = random_quiz
        chatroom.game_mode = true
        chatroom.save!


        # chatroom.update(quiz_id: random_id)
        # chatroom.update(game_mode: true)
      else

        message = "Quiz is already running. quiz question is '#{chatroom.quiz.question}'"

      end
    when chatroom.quiz.answer.downcase
      if chatroom.game_mode
        message_user = "Robot"
        message = current_user.name + " got the question correct!"
        score = self.current_user.score || 0
        self.current_user.update(score: score+1)
        chatroom.update(game_mode: false)
      end
    when /@RESET_QUESTION/i
      message_user ="RESETBOT"
      message = "Quiz Reset"
      chatroom.update(game_mode: false)


    when /@wdi3/i
      message_user = "#{current_user.name}"
      message = "WDI 3 FOR LIFE! "
    when /@info/i
      message_user = "Info_Bot"
      message= "To run a quiz, type @quiz.  To reset a quiz type @reset_question"

# Test drive this out.
    when /<script>/i
      message_user= "HACKER"
      message= "DIS HACK"
    else
      # publish message
    end

    #  need to add an else logic maybe add some seed logic





    # TODO
    #  if message =='@ROBOT_QUIZ'  post a question
    # if message == '@ANSWER' see if its correct....sorry that isnt the correct answer.
    #put in the logic in the model so that I can specify that:
    # current_question=  the random question sample
    #  current_answer = the random answer to that question.



    # running all publishing events through faye in our controller.
    require 'eventmachine'

    EM.run {
      client = FayeRails.client

      # client.subscribe('/messages') do |message|
      #   puts message.inspect
      # end

      client.publish('/messages/public', 'msg' => message, username: message_user, scores: user_scores)
    }
    # expecting to render a view if we dont do anything.
    render nothing: true, :status => :ok
  end
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
  def front
  end

  def room
    # we will use this later when we want to specify other chatrooms
    # @chatroom = Chatroom.find(params[:id])
    # we need to instantiate the table in order to call on the table
    @users = User.all.order("score DESC").where.not(score: 'nil')
    respond_to do |format|
      format.html
      format.json {render json: @users}
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate_user, except: [:destroy]

  def index
  end

  def new
  end


  def create
    user = User.from_omniauth(request.env['omniauth.auth'])
    self.current_user = user
    Rails.logger.info "current_user=#{self.current_user}"
    cookies[:user_id] = user.id
    flash[:success] = "Hello, #{user.name}!"
    redirect_to "/chatroom"
  end

  def destroy
    cookies.delete(:user_id)
    flash[:success] = "See you!"
    redirect_to root_url
  end

  protected

  def auth_fail
    render text: "You've tried to authenticate via #{params[:strategy]}, but the following error occurred: #{params[:message]}", status: 500
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/chatroom/room.html.erb
<div class="chat_container container"  >

 <p class="alert"> Welcome to the chat room <%= current_user.name %>! Type @info for info! All answers are in lowercase!</p>
 <div class = "row">
    <%= form_tag chat_messages_path, remote: true do %>
      <%= text_field_tag :message %>
       <%= submit_tag "Send" %>
      <%= hidden_field_tag :chatroom_id, 1 %>
    <!-- we are leaving this here so that later we can dynamically call on different chatrooms. the above form should be changed to :chatroom_id , @chatroom.id instead of a value of 1-->
      <% end %>
    <div id="chat_room" class= "col-md-8" style ="overflow-y:scroll">
   </div>
    <div id= "score_box" class = "col-md-4">
      <h1>Top Scorers</h1>
      <ol id="top_score">
        <% @users.each do |user| %>
        <li><%= user.name %>, <%= user.score %></li>
        <% end %>
      <!--   <li><%= current_user.name %>, <%= current_user.score %></li> -->
      </ol>
    </div>
  </div>
</div>

</div>

app/views/chats/room.html.erb
<script>
  $(function() {
    // Create a new client to connect to Faye
    var fayeUrl = '/faye'
    // var fayeUrl = 'http://10.1.8.241:9292/faye'
    // var fayeUrl = 'https://lit-ravine-1969.herokuapp.com/faye'
    var client = new Faye.Client(fayeUrl);
    //for loalhost, all you need is var client = new Faye.Client('http://localhost:9292/faye')


// Subscribe to the public channel. This allows connected users to receive chats.this the <p> tags are going to be used  to take.  Its a method that takes in two arguments.  Where it subscribes to and then the data or mesage.(http://faye.jcoglan.com/browser/subscribing.html). this is how people receive other peoples chats.
    var public_subscription = client.subscribe('/messages/public', function(data) {
      $('<p></p>').html(data.username + ": " + data.msg).appendTo('#chat_room');
    });

     // Our own private channel. Allows an individual to receive messages on a private terminal.
    var private_subscription = client.subscribe('/messages/private/<%= session[:username] %>', function(data) {
      $('<p></p>').addClass('private').html(data.username + ": " + data.msg).appendTo('#chat_room');
    });

  });
</script>

<div class="chat_container">
  <div id="chat_room">
    <p class="alert"> Welcome to the chat room <%= current_user.name %>! </p>
  </div>

  <!-- <form id="new_message_form">
    <input type="text" id="message" name="message">
    <input type="submit" value="Send">
  </form> -->
  <%= form_tag chat_messages_path, remote: true do |f| %>
    <%= text_field_tag :message %>
    <%= submit_tag "Send" %>
  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DNDBabelBabble</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <!-- not sure if i need the above tag, need to point it to a different url -->
  <%= csrf_meta_tags %>
</head>
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/chatroom">
        <p> BabelBabble </p>
      </a>
    </div>
      <ul class= "nav navbar-nav navbar-right">
        <% if cookies[:user_id] %>
          <p class="navbar-text">Signed in as <%=current_user.name%></p>
          <p class="navbar-text"><%= link_to "Sign Out", "/sign_out" %></p>
       <%else %>
        <%= link_to "Connect With Facebook", "/auth/facebook" %>

        <%end%>
      </ul>

  </div>
</nav>
  <%= yield %>
</body>
</html>